name: Deploy Script Action
description: "An action to execute a shell script"
runs:
  using: "composite"
  steps:
  - name: Run script
    run: bash -e ./.github/actions/deploy/script.sh
    shell: bash
