name: Quality Script Action
description: "An action to execute a shell script"

inputs:
  SONARQUBE_URL:
    required: true
  SONAR_TOKEN:
    required: true
  PROJECT_KEY:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set script permissions
      run: chmod +x ./.github/actions/quality/script.sh
      shell: bash
    - name: Run script
      run: bash -e ./.github/actions/quality/script.sh
      shell: bash
