on:
  workflow_dispatch:
    inputs:
      SONARQUBE_URL:
        required: true
        type: string
      SONAR_TOKEN:
        required: true
        type: string
      PROJECT_KEY:
        required: true
        type: string

jobs:
  pysonar-scanner:
    steps:
      - name: Set script permissions
        run: chmod +x ./.github/actions/quality/script.sh
      - name: Run script
        run: bash -e ./.github/actions/quality/script.sh
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

        #with:
        #  SONARQUBE_URL: ${{ inputs.SONARQUBE_URL }}
        #  SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        #  PROJECT_KEY: ${{ inputs.PROJECT_KEY }}
