on:
  workflow_call:
    inputs:
      SONARQUBE_URL:
        required: true
      SONAR_TOKEN:
        required: true
      PROJECT_KEY:
        required: true

jobs:
  pysonar-scanner:
    runs-on: self-hosted
    steps:
      - name: Set script permissions
        run: chmod +x ./.github/actions/quality/script.sh
      - name: Run script
        run: bash -e ./.github/actions/quality/script.sh
        with:
          SONARQUBE_URL: ${{ inputs.SONARQUBE_URL }}
          SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
          PROJECT_KEY: ${{ inputs.PROJECT_KEY }}
