inputs:
  SONARQUBE_URL:
    required: true
  SONAR_TOKEN:
    required: true
  PROJECT_KEY:
    required: true

runs:
  using: "composite"
  steps:
    - name: Run script
      run: bash -e ./.github/actions/quality/script.sh
      shell: bash
      env:
        SONARQUBE_URL: ${{ inputs.SONARQUBE_URL }}
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        PROJECT_KEY: ${{ inputs.PROJECT_KEY }}
