name: Simple Web Application Workflow
on:
  push:
    branches:
      - master
jobs:
  pre-deploy:
    runs-on: self-hosted
    environment: Develop
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get dependencies
        uses: ./.github/actions/install
      - name: Build
        uses: ./.github/actions/build
      - name: Quality Assurance
        uses: ./.github/actions/quality
        with:
          SONARQUBE_URL: ${{ env.SONARQUBE_URL }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          PROJECT_KEY: ${{ github.repository }}
      - name: Publish artifacts
        uses: ./.github/actions/publish
  deploy:
    runs-on: self-hosted
    needs: pre-deploy
    steps:
      - name: Validate
        uses: ./.github/actions/validate
      - name: Deploy
        uses: ./.github/actions/deploy
