name: Simple Web Application Workflow
on:
  push:
    branches:
    - master
jobs:
  pre-deploy:
    permissions: write-all
    runs-on: self-hosted
    environment: Develop
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Get dependencies
      uses: ./.github/actions/install
    - name: Build
      uses: ./.github/actions/build
      with:
        APP_NAME: ${{ github.event.repository.name }}
        COMMIT_SHA: ${{ github.sha }}
    - name: Quality Assurance
      uses: ./.github/actions/quality
      with:
        SONARQUBE_URL: ${{ vars.SONARQUBE_URL }}
        SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        PROJECT_KEY: ${{ github.event.repository.name }}
    - name: Publish artifacts
      uses: ./.github/actions/publish
      with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_USER: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
  deploy:
    runs-on: self-hosted
    needs: pre-deploy
    steps:
    - name: Validate
      uses: ./.github/actions/validate
    - name: Deploy
      uses: ./.github/actions/deploy
